### ISSUE TITLE
schema设置tag属性为'object'时，遇见的问题

### ISSUE THREAD

**Issue by a869246700** [lisiyizu/el-form-schema#2]
如果components对象中，若存在label字段时，它会默认在页面上<label>标签设置 width: '0px'，导致label显示时是垂直向下拉长整个页面。
`
model: {},
      schema: {
        date: { 
          tag: 'el-date-picker', 
          required: true, 
          label: '日期', 
          inline: true, 
          props: { type: 'daterange' },
          slot: { after: '-' }
        },
        time: { tag: 'el-time-select', inline: true},
        obj: {
          tag: 'object',
          inline: true,
          label: '对象',
          required: true,
          components: {
            input: { tag: 'el-input', label: '深层次飒飒飞洒发撒', required: true },
            input2: { tag: 'el-input', label: 'g大公司搞设定高度时高时低', required: true },
            input3: { tag: 'el-input', label: '都是噶所多撒多撒多', required: true }
          }
        }
      }
`

**Comment by lisiyizu** [comment]
![image](https://user-images.githubusercontent.com/12014252/106748707-92293600-6660-11eb-97da-f5688e33ed55.png)

![image](https://user-images.githubusercontent.com/12014252/106748753-9ead8e80-6660-11eb-81a1-c6dc12c15629.png)
